name: app
description: Flutter project template.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_launcher_icons: ^0.14.3
  freezed_annotation: ^2.2.0
  go_router: ^14.2.7
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.6
  http: ^1.1.0
  json_serializable: ^6.7.1
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.3.1
  translator_plus: ^1.0.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.2.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.6
  custom_lint: ^0.7.1
  riverpod_lint: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: "assets/icon.png"
  adaptive_icon_background: "#121212"
  web:
    generate: true
    image_path: "assets/icon.png"
