name: app
description: Flutter project template.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  freezed_annotation: ^2.2.0
  go_router: ^10.1.2
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.0.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.2.1
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
