name: app
description: Flutter project template.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  freezed_annotation: ^2.2.0
  go_router: ^10.1.2
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.6
  http: ^1.1.0
  json_serializable: ^6.7.1
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.2.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/
