{
  "sksl": {
    "entrypoint": "simple_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 resolution;\nuniform float amount;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvec3 FLT_flutter_local_hsv(float h, float s, float v)\n{\n    return (((clamp(abs((fract(vec3(h) + vec3(0.0, 0.66600000858306884765625, 0.333000004291534423828125)) * 6.0) - vec3(3.0)) - vec3(1.0), vec3(0.0), vec3(1.0)) - vec3(1.0)) * s) + vec3(1.0)) * v;\n}\n\nvoid FLT_main()\n{\n    vec2 coord = FLT_flutter_local_FlutterFragCoord();\n    vec2 resolution_1 = resolution;\n    vec2 uv = (coord - (resolution_1 * 0.5)) / vec2(resolution_1.y);\n    float param = length(uv * 0.100000001490116119384765625) + amount;\n    float param_1 = 1.0;\n    float param_2 = 1.0;\n    fragColor = vec4(FLT_flutter_local_hsv(param, param_1, param_2), 0.5);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "resolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "amount",
        "rows": 1,
        "type": 10
      }
    ]
  }
}